### ISSUE TITLE
document typescript version

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/amaro#10]
We need to document the supported latest typescript version.
maybe we can get it from swc @kdy1

**Comment by kdy1** [comment]
All TypeScript features except the stage 3 decorator proposal are supported, so SWC supports 5.5.4 for now. We will always implement the support the latest TypeScript before it's published.

**Comment by marco-ippolito** [comment]
> All TypeScript features except the stage 3 decorator proposal are supported, so SWC supports 5.5.4 for now. We will always implement the support the latest TypeScript before it's published.

Is it possible to add this information somewhere in the package, so when we update swc we can read it and update it?

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/pull/9334 adds the supported TypeScript version to the `@swc/wasm-typescript` package. The next stable version will have it documented in README.md

**Comment by marco-ippolito** [comment]
we changed the way we interact with swc, we now get the source code from the release and build it ourself, as per node policy, so we technically dont use the `@swc/wasm-typescript` per se

**Comment by kdy1** [comment]
So do you prefer documenting it in the main README.md?

**Comment by marco-ippolito** [comment]
No I mean, we use swc `./scripts/build.sh` if the README was inside that pkg output would be great, or wherever it is we can pull it in https://github.com/nodejs/amaro/blob/86cd3aa1d43d0e2e5e9e8d9257d420583208d8e7/tools/Dockerfile#L39

**Comment by kdy1** [comment]
The README file lives at `bindings/binding_typescript_wasm/README.md` so it will be pulled.

https://github.com/swc-project/swc/tree/66f31c0af46dea60c51e4155a8887a5d2b441da3/bindings/binding_typescript_wasm

**Comment by marco-ippolito** [comment]
I had a look in the release source code https://github.com/swc-project/swc/releases/tag/v1.7.1 and the README is missing

**Comment by kdy1** [comment]
Oops, publish action for 1.7.2 failed. https://github.com/swc-project/swc/actions/runs/10089340507/job/27896627211
I'll fix it right away
