### ISSUE TITLE
SWC update does not trigger CI

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/amaro#101]
The PR is created by the swc update action. The CI does not start

**Comment by legendecas** [comment]
FWIW, a @nodejs-github-bot's token can be requested at https://github.com/nodejs/admin/blob/main/request-an-access-token.md

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.
> https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow

**Comment by marco-ippolito** [comment]
I updated with the new token but it still fails:
https://github.com/nodejs/amaro/actions/runs/12506701416/job/34892036019


Change: https://github.com/nodejs/amaro/commit/9ceb649a8e94842133b6b7ea736f5302e0794d89

**Comment by legendecas** [comment]
I granted @nodejs-github-bot write access to this repo. Restarted the job and it works now: https://github.com/nodejs/amaro/pull/139
