### ISSUE TITLE
Upstream swc asi fix

### ISSUE THREAD

**Issue by acutmore** [nodejs/amaro#11]
Note: there is an upstream fix for an ASI issue: https://github.com/swc-project/swc/issues/9331#issuecomment-2249255068

cc @kdy1

**Comment by kdy1** [comment]
I triggered the publish action!
https://github.com/swc-project/swc/actions/runs/10089340507

**Comment by marco-ippolito** [comment]
is this fixed by 1.7.2? if so we can close since I've updated it

**Comment by acutmore** [comment]
Yep. Fix is included. Thanks @marco-ippolito
