### ISSUE TITLE
`mode: "transform"` introduces redundant newline suffix

### ISSUE THREAD

**Issue by robpalme** [nodejs/amaro#140]
All [the transform test snapshots](https://github.com/nodejs/amaro/blob/main/test/snapshots/transform.test.js.snapshot) show that SWC is injecting a `\n` suffix in the JS emit that was not present in the input.

This does not seem harmful given that the transform case is allowed to move lines around.  It just seems like a minor inefficiency.  I'm documenting it here for awareness and to see if folk agree.

**Comment by marco-ippolito** [comment]
cc @kdy1

**Comment by kdy1** [comment]
Should I trim the newline at the end, or skip only the last newline?

**Comment by marco-ippolito** [comment]
I think the point is not to add anything unnecessary.
In the example of `using r = 0;` there is no new line so its not useful to add it. In the code you trasform its fine:

```ts
enum Colors { Red, Green, Blue }
```
its ok to add the new line:
```js
var Colors; (function (Colors)\n { Colors[Colors["Red"] = 0] = "Red";\n Colors[Colors["Green"] = 1] = "Green";\n Colors[Colors["Blue"] = 2] = "Blue"; })(Colors || (Colors = {}));
```

**Comment by robpalme** [comment]
There's no urgency to act here.

I checked and transform mode always fully reformats the code, normalizing all non-semantic whitespace. Meaning there's currently no attempt to preserve original line numbers. So the as-is behavior seems fine.

Feel free to re-open if anyone thinks otherwise.
