### ISSUE TITLE
Support for Enums and Namespace Types in Strip-Only Mode

### ISSUE THREAD

**Issue by mertcanaltin** [nodejs/amaro#22]
Hello,

I encountered an issue while using the `transformSync` function where it appears that enums and namespace types are not supported in strip-only mode. Specifically, the function fails to strip type annotations from enums and namespaces, leading to errors in the transformation process

**Comment by marco-ippolito** [comment]
It is by design https://github.com/nodejs/loaders/issues/217

**Comment by dionysiusmarquis** [comment]
I just want to leave a quck "workaround", at least for string enums

```ts
const Direction = {
  Up = "up",
  Down = "down",
  Left = "left",
  Right = "right",
} as const;
type Direction = (typeof Direction )[keyof typeof Direction ];
```
Important is `as const`. This way type `Direction` will be `"up" | "down" | "left" | "right"`, wich should work pretty much (or maybe axacly?) like a string enum.

Here the same result with a custom helper type
```ts
type StringEnum<T extends Record<string, string>> = T[keyof T];
...
type Direction = StringEnum<typeof Direction>;
´´´
