### ISSUE TITLE
Automate SWC update

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/amaro#28]
Create a gh action that runs weekly and check for swc updates.
It launches the update script and also builds the wasm `./tools/build-wasm.js`
It should open a PR with the changes

**Comment by Jayllyz** [comment]
Im working on it

**Comment by marco-ippolito** [comment]
Fixed by https://github.com/nodejs/amaro/pull/32

**Comment by Jayllyz** [comment]
😭 I should have tested it before my push... it seems that this PR action works differently than the one I used the first time, the github token is missing + i'm getting for an unknown reason :
<img width="435" alt="image" src="https://github.com/user-attachments/assets/373d6362-3ce8-4715-bae2-3139abcd48c7">

Sorry..

**Comment by marco-ippolito** [comment]
Told you to run it in a fork 😄 its fine
