### ISSUE TITLE
commitlint allow commit body > 100

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/amaro#41]

**Comment by YashrajKupekar17** [comment]
I would solve the issue. Can u just describe it a little

**Comment by marco-ippolito** [comment]
this pr is failing the commit lint https://github.com/nodejs/amaro/pull/40 

https://github.com/nodejs/amaro/actions/runs/10242091104/job/28331286717?pr=40

It's ok to increase the commit body length

**Comment by marco-ippolito** [comment]
fixed by https://github.com/nodejs/amaro/pull/40
