### ISSUE TITLE
Dependency list

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/amaro#49]
This is the list of dependencies license used by the `swc` version we use:
https://github.com/nodejs/amaro/blob/4ffa2cd096ba273e84521657d8a6cf92958f31cc/deny.toml#L7C1-L20C2
```
[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "0BSD",
    "CC0-1.0",
    "Unicode-DFS-2016",
    "BSL-1.0"
]
```
This list is checked by cargo deny, and they might be dev dependencies.
Note that we bundle swc in a wasm file.

In nodejs/node we only added amaro license https://github.com/nodejs/node/pull/53725/files#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7R133-R157

ping @nodejs/tsc as fyi

**Comment by targos** [comment]
We definitely need to add at least the `swc` license to `node`, since we distribute it in "Object form" (the wasm file)

**Comment by targos** [comment]
In fact, `amaro` should do it as well (in the npm package).

**Comment by marco-ippolito** [comment]
> In fact, `amaro` should do it as well (in the npm package).

so we should add in the `dist` folder of the npm package https://www.npmjs.com/package/amaro?activeTab=code, the license of swc?

**Comment by targos** [comment]
I think so.

**Comment by marco-ippolito** [comment]
we got [swc license](https://github.com/nodejs/amaro/pull/53) (which was not being included), I need to add it in the released bundle

**Comment by marco-ippolito** [comment]
as soon as swc releases their updated license (I sent a PR https://github.com/swc-project/swc/pull/9417) I will add it to the dist
