### ISSUE TITLE
update transform tests to match node

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/amaro#60]
We added a new option to `transformSync`
https://github.com/nodejs/node/pull/54283/files#diff-fddf8a06747f8c9e83cd2a3ebee0f53dbd790567ce018044e70bd0ffbbcc815eR357-R370

We need to match in tests and snapshots

**Comment by mertcanaltin** [comment]
I wonder if this includes the newly added transform tests?

**Comment by marco-ippolito** [comment]
> @marco-ippolito I would like to pick this up.

sure go ahead

**Comment by raashidanwar** [comment]
> > @marco-ippolito I would like to pick this up.
> 
> sure go ahead

Would be glad if you give me more details and any references to start.

**Comment by raashidanwar** [comment]
@marco-ippolito The test and snapshots change will be in node not in amaro right?

**Comment by marco-ippolito** [comment]
It will be in Amaro

**Comment by raashidanwar** [comment]
@marco-ippolito I can see the option is already there in the test case https://github.com/nodejs/amaro/blob/main/test/transform.test.js.
Can you tell me what other new filed we need to add to the test case?

**Comment by raashidanwar** [comment]
Here is the PR 👉 https://github.com/nodejs/amaro/pull/67 @marco-ippolito , All the options are already there.

**Comment by ScrabyQ** [comment]
@marco-ippolito
Do you mean implementing similar tests from this [PR](https://github.com/nodejs/node/pull/54283/files#diff-785af8fb449050de8efaa254921760366084825eaca01d66d49367129b01b667R8-R116) in amaro?

**Comment by marco-ippolito** [comment]
fixed
